### ISSUE TITLE
Document Authorization/Anvil processes

### ISSUE THREAD

**Issue by aiboyles** [coralproject/docs#24]
- Determine how Anvil fits into the current ecosystem.
- Document Anvil's role and processes as they currently stand.
- Document how Anvil integrates with Xenia.
- Add Anvil/Authorization to the Architectural Overview diagram.

**Comment by aiboyles** [comment]
Backlogging this, since Anvil is not currently really integrated into Coral. Revisit once this gets a bit further along.

**Comment by kgardnr** [comment]
This is a WIP, closing
