### ISSUE TITLE
Add more technical info, incl aggregates, to FAQ page

### ISSUE THREAD

**Issue by aiboyles** [coralproject/docs#34]
Currently, the FAQ page includes some fairly basic non-technical information.

I plan on using Greg's FAQ documents on the Google Drive to add information about aggregates, filters, and other information that may be for more technical users.

**Comment by sfphoenix** [comment]
This FAQ? ['FAQ from partners' - We have Elastisearch, Postgres, data aggregation options](https://docs.google.com/document/d/1FxDzzqi8uKWsl4v9wndD9W-f6aO_Xq56ALJMOwQ0FqQ/edit)

**Comment by kgardnr** [comment]
We should discuss with @jde, @losowsky & @gjbarber because this FAQ focuses primarily on Trust, and also may be outdated.

**Comment by kgardnr** [comment]
I'm closing this because it is outdated.
