### ISSUE TITLE
Elkhorn documentation

### ISSUE THREAD

**Issue by aiboyles** [coralproject/docs#38]
Flesh out current Elkhorn documentation:

- [x]  Greater description of what Elkhorn does and how it works.
- [ ]  How to contribute/write a new widget (using this as starting point): https://github.com/coralproject/elkhorn/blob/master/CONTRIBUTING.md
- [x] API documentation.
- [x] Redraw Elkhorn diagrams in new draw.io diagram format.

**Comment by aiboyles** [comment]
I need to flesh out the "Contributing a new widget" portion, and am also waiting on additional info for the API.

**Comment by aiboyles** [comment]
Pending review from @pablocubico.

**Comment by pablocubico** [comment]
Great work! These docs look great. Just a couple of minor notes:

# Ask Composer
Partial states may be stored locally, even if S3 has been set up
-- Not sure what this line means... 

# Set up configuration file
If you installed Pillar locally as a Docker container, pillarHost should be http://10.0.4.105:8080. http://10.0.4.105 is the URL generated by Docker.
-- I'm not familiar with these IPs, check with Eugene in any case

# Contributing an answer field
Extend the AskInterface interface: Your question field class will extend the AskField interface.
-- Typo! It should say "Extend the AskField interface"

**Comment by aiboyles** [comment]
_ping_ @pablocubico can you make sure you review the API portion? You can ping me on Slack with any questions.

**Comment by pablocubico** [comment]
Looks good to me, except for the missing example messages!

**Comment by pablocubico** [comment]
@jtnelson here you go:
https://gist.github.com/pablocubico/f3eaae62600d497e33eaaa865425ab15
(probably you'll want to hide urls or things that shouldn't go there)

I think we can delete the examples for `iframe` and `preview`, as those will not return JSON but an entire JS/HTML file for the iframe or the preview.
