### ISSUE TITLE
Link behind VPN

### ISSUE THREAD

**Issue by gabelula** [coralproject/docs#47]
There is a link in the docs that is behind our VPN because it has data that can not be public. Check links without VPN.

**Comment by aiboyles** [comment]
This appears to be the data dump link. Eugene updated the permissions on it so it can be accessed without VPN. There are apparently other options for checking links, like bots, that I'll investigate. I believe the data dump link is the only thing currently that cannot (or couldn't) accessed without VPN, but it's worth looking into for the future.

**Comment by gabelula** [comment]
Yes. I think that one was the link.
