### ISSUE TITLE
Expand documentation on API endpoint Xenia queries

### ISSUE THREAD

**Issue by gabelula** [coralproject/docs#48]
We want people to use the pillar API to send data into Trust as well as Xenia for quering aggregations. This is a very good example for documentation on how to use a REST API:

https://stripe.com/docs/api/curl#intro

**Comment by sfphoenix** [comment]
@gabelula which elements in that Stripe url resonate most for you?

- API call via curl
- libraries in multiple languages
- explanation of the endpoint usage
- syntax highlighting
- docs layout

The thing that stands out is the single page which allows for a quick search via 'Cmd+F' (Mac) or 'Ctrl+F' (Windows).

**Comment by gabelula** [comment]
- it is clear on how to use the API
- it includes libraries in multiple languages
- explanation of the endpoint usage

**Comment by sfphoenix** [comment]
Thanks for the clarification @gabelula ;-)

**Comment by kgardnr** [comment]
@sfphoenix (cc @gabelula & @jde) - i think we should break this down into work for each API we have; and questionable if we should do it for pillar if we are planning on eventually deprecating? thoughts?

**Comment by sfphoenix** [comment]
Refining this issue to be placeholder for Xenia queries as Shelf (Pillar) API has a separate issue [https://github.com/coralproject/docs/issues/37](https://github.com/coralproject/docs/issues/37)
