### ISSUE TITLE
Explore different API documentation platforms

### ISSUE THREAD

**Issue by aiboyles** [coralproject/docs#49]
David pointed to Swagger as an attractive documentation platform specifically for APIs. While I'd prefer to keep everything on one platform in one place, I agree that for larger APIs like Pillar it may be worth turning to an API-specific platform. I'll take a look at Swagger and Slate and see what we might want to use and how that can fit into our current documentation.

**Comment by sfphoenix** [comment]
+1 on Swagger

**Comment by kgardnr** [comment]
Closing, will turn into stories to implement Swagger for automated API documentation.
