### ISSUE TITLE
Add build process to deploy script

### ISSUE THREAD

**Issue by davidgljay** [coralproject/docs#56]

**Comment by davidgljay** [comment]
This is complete, unfortunately it looks like we've completed our free trial with Iron.io. We're not locked out of our account until we contact sales (a bad UX). We should be fine with their free tier, I've put in a request to their sales dept to switch us to that.

@losowsky

**Comment by kgardnr** [comment]
Thanks @davidgljay!

**Comment by losowsky** [comment]
We should be back in our account now.
