### ISSUE TITLE
organize repo labels

### ISSUE THREAD

**Issue by sfphoenix** [coralproject/docs#66]
for visual scanning and effective issue/PR filtering

**Comment by sfphoenix** [comment]
![coralproject_docs_labels](https://cloud.githubusercontent.com/assets/10662816/19322067/77078c56-906c-11e6-9732-cbe59bbd36f7.jpg)

**Comment by sfphoenix** [comment]
review request @kgardnr

**Comment by gabelula** [comment]
what is "p1" ?
