### ISSUE TITLE
Where's the Proxy project?

### ISSUE THREAD

**Issue by jonathansp** [coralproject/docs#77]
Hi everyone

We've been starting to do some tests in Ask and Trust platforms at @globocom. After reading the [docs](https://docs.coralproject.net/quickstart/install/#get-the-source-code) and running docker-compose, we came across an unexpected error:

``` javascript
oidc-client.js:156 No metadataUrl configured on settings
```

We tried to pull Proxy's code again so as to check if we wouldn't work on an outdated code, but I'm afraid this project has gone. 😄  What should we do?

**Comment by jde** [comment]
Hi @jonathansp. Thanks for trying out Ask and Trust. Sorry you hit those issues.  We temporarily pulled the install code as it was giving us persistent problems.  We are days away from having a reworked installation flow up and running, which will include our authorization and ssl support.  

We will update this ticket once the new flows are up. Thanks for letting us know!

Best,
David

**Comment by jonathansp** [comment]
Hi @jde, thanks! 

I was wondering if we should try out Ask/Trust without docker installation or wait for your update. What do you think?

**Comment by jtnelson** [comment]
@jonathansp We're hoping to release the update later today so please stay tuned if your timeline permits!

**Comment by kgardnr** [comment]
Hi @jonathansp, please check out the latest Ask Install docs here: https://docs.coralproject.net/products/ask/

You can also reach out to Jeff directly here: jeff@mozillafoundation.org with any questions!

Thanks! :)
Kim & The Coral Team
